- app/Photo.php
If the Imagick extension isn't installed `$error = false` and the backup
GD resizing doesn't get run. `Photo::createMedium` still returns true so
the medium (and small) flags get set in the DB.
> Resizes images if Imagick extension is missing

- app/Http/Controllers/PhotoController.php
- app/ModelFunctions/Helpers.php
- app/ModelFunctions/PhotoFunctions.php
- database/migrations/2018_08_03_110935_create_albums_table.php
- database/migrations/2018_08_03_110936_create_photos_table.php
- database/migrations/2018_08_03_111324_create_logs_table.php
- database/migrations/2018_08_15_102039_move_albums.php
- database/migrations/2018_08_15_103716_move_photos.php
- database/migrations/2018_10_30_135411_sharing.php
- database/migrations/2019_02_03_133007_change_id_type.php
This should simplify the migration from the v3 to the v4 and reduce the risk of collisions
> Use BigInteger instead of simple integer for ids.

- app/Album.php
- app/Configs.php
- app/Console/Commands/medium.php
- app/Console/Commands/small.php
- app/Http/Controllers/AlbumsController.php
- app/Http/Controllers/PhotoController.php
- app/Image/GdHandler.php
- app/Image/ImageHandlerInterface.php
- app/Image/ImagickHandler.php
- app/ModelFunctions/PhotoFunctions.php
- app/Photo.php
- database/migrations/2019_02_23_222617_add_hidpi.php
- public/dist/main.js
- public/dist/view.js
This merge request addresses https://github.com/LycheeOrg/Lychee/issues/198.
It's a pretty large patch so allow me to provide an overview/motivation for why I coded it the way I did.  I can of course make any modifications you deem necessary to make it acceptable for merging.
Lychee currently supports HiDPI ("retina") for the square thumbnails only, by creating `@2x` files on the server side during image upload and assuming on the frontend side that those files are always present (the `@2x` names are unconditionally used in `srcset` when generating HTML).
To keep things configurable, I added three new options to the `configs` table: `thumb_2x`, `small_2x`, and `medium_2x`.  Only the first one defaults to 1, to mimic the current behavior.  The others need to be set to 1 manually to …
> Server support for full HiDPI

- app/Image/ImagickHandler.php
- app/ModelFunctions/PhotoFunctions.php
Setting {small,medium}_max_width to 0 was fully supported but setting the height was not.
Fixes #99.
> Support 0 *_max_height config

- app/Console/Commands/medium.php
- app/Console/Commands/medium2x.php
- app/Console/Commands/small.php
- app/Console/Commands/small2x.php
Provide additional diagnostics on stdout.
Exclude movies from the process.
Only count successful image creations towards the limit.
> Make the small/medium/2x commands easier to use

- app/Album.php
I noticed some strange misbehavior with HiDPI images. On investigation I found a minor bug in the front end (I will submit a separate commit for that) but also a major issue on the server side: changes to `App/Album.php` from commit 0a43348 got lost. @ildyria, this appears to have happened during your commit 7e14093.
This PR reapplies the lost changes.
> Reapply changes lost in 7e14093

- app/Http/Controllers/PhotoController.php
This is a pretty trivial patch needed to add HiDPI support to the Frame mode. The bulk of it will be in a separate PR for the front end.
The front end needs more info about the image to fill in the `srcset` and `sizes` tags; the easiest way to accomplish that is to simply return the whole Photo object which contains everything we may possibly need, and we already have the code to pass it.
> Add HiDPI support to Frame mode

- app/Album.php
When there's a public, but password-protected album, when listing albums without being logged in, the front end generates an error in `albums.parse` because `albums.thumbs` is undefined. No albums are displayed as a result. It works fine with Lychee v3 though. This patch ensures that we always generate the `thumbs`/`thumbs2x`/`types` arrays in our response to the front end, even if they end up being empty.
> Always create thumbs/thumbs2x/types for albums

- database/migrations/2019_02_23_222617_add_hidpi.php
Fixes #144 
Makes the hidpi migration more robust and restartable.
Since I don't think we can pass any arguments to migrations, I opted for a slightly unsightly solution of asking user to create a file with a particular name (contents irrelevant) if they want to ignore the problem and continue without small/medium images. Let me know if this is OK.
I tested the ignoring and it works but is not perfect. The test for missing thumb@2x photos gets triggered so thumb2x gets set to 0 for each photo. And we don't currently have any way to reset it. Should we extend `php artisan generate_thumbs` to add support for square thumbs generation as well?
> Don't crash when photos are missing

- app/Album.php
Server-side fix for #139
This basically duplicates the condition from `AlbumFunctions::prepare_albums()`, only this time for subalbums, and in a less round-about way :smirk:
> Don't return thumbs of password-protected subalbums

- app/Http/Controllers/DiagnosticsController.php
Diagnostics fails with "Server error" if user.css does not have sufficient permissions. I just tweaked the code to match the lines above the failing lines and that seems to have fixed it.
> Don't fail if user.css is not writeable

- app/Locale/ChineseSimplified.php
- app/Locale/Dutch.php
- app/Locale/English.php
- app/Locale/French.php
- app/Locale/German.php
- app/Locale/Swedish.php
- resources/views/gallery.blade.php
Finally takes care of my pet project #94
Front end part is at https://github.com/LycheeOrg/Lychee-front/pull/52
> Add fullscreen support to album and photo views

- app/Http/Middleware/VerifyCsrfToken.php
- database/migrations/2019_03_29_185414_add_api_key.php
Check the `Authorization` header to make sure an API key is present and matches what is in the config table (assuming what is a valid string)
> skip csrf verification if an api key is set and present

- app/Http/Controllers/DiagnosticsController.php
- app/ModelFunctions/AlbumFunctions.php
- app/ModelFunctions/Helpers.php
- app/ModelFunctions/PhotoFunctions.php
- database/migrations/2019_04_07_193345_fix_32bit.php
Fixes #163
This is a first attempt at support for PHP installations with 32-bit integers. This should address #163.
Not having a 32-bit system around, I wasn't able to test it properly, but hopefully others will be able to confirm if it works.
I didn't add database migration yet so don't try it when migrating an existing v3 installation. For now, it's for fresh v4 installations only. @ildyria can you help with the migration? I'm guessing we need a way to convert those big integers to strings outside of PHP, so that we can then chop the last 4 digits off and store the remaining 32-bit int. Only how to do this? Databases are not my forte.. Also, I'm assuming that we can keep the "big" column types even on 32-bit systems, so long as we ensure that any data we put in is 32-bit?
Here's an …
> Add support for short ids on 32-bit systems

- composer.json
- composer.lock
Fixes https://github.com/LycheeOrg/Lychee-Laravel/issues/26 (was already closed but for reference @jeyca )
Add the following composer dependency to `--dev`:
- https://github.com/itsgoingd/clockwork
- https://github.com/stefanzweifel/laravel-stats
This PR will require you to do a `composer install` if you are using the dev mode.
- Clockwork is a profiler, it should be able to replace the Laravel debug bar which we can't use because of the full REST API. The results can be accessed via http://example.com/__clockwork/app If you are using `composer install` without `--no-dev` in production, this package will only be enabled if `APP_DEBUG` is set to `true`.
- Laravel-stats provides a command line simple stat info accessible via artisan:
```
▶ php artisan stats …
```
> add clockwork and stats

- app/Http/Controllers/DiagnosticsController.php
- app/Http/Controllers/SessionController.php
- app/Http/Controllers/SettingsController.php
- app/Metadata/GitHubFunctions.php
- app/ModelFunctions/Helpers.php
- app/ModelFunctions/SessionFunctions.php
- app/Providers/AppServiceProvider.php
- routes/web.php
This PR centralize GitHub interactions (check for updates, check the current version of the installation) and improve the Diagnostics to inform the user whether it's installation is up to date or not.
It also set a timeout to the check for updates to 1 second instead of 1 minute as previously defined in php.ini.
> Improve update check, and add it to diagnostics

- app/Configs.php
Fixes #164
```
Request URL: http://127.0.0.1:90/api/Settings::saveAll
Request Method: POST
Status Code: 500 Internal Server Error
message: "Server Error"
```
```php
{
"message": "Creating default object from empty value",
"exception": "ErrorException",
"file": "/app/Lychee-Laravel/app/Configs.php",
"line": 103,
"trace": [
{
"file": "/app/Lychee-Laravel/app/Configs.php",
"line": 103,
"function": "handleError",
"class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
"type": "->"
},
]
}
```
then I found the reason:
```
$config = Configs::where('key', '=', $key)->first();
//without Check $config is null or not
$config->value = $value;
```
but, this is not the root cause.
the reason is that the method get a `key` param with an invalid value `Settings::saveAll`
of course this does not …
> monkey patch:  fixup app/Configs 'Creating default object from empty value' error

- app/Http/Controllers/SearchController.php
It looks like one of the recent commits (34f108f9603b8f08d24684ba5fd323130815c533?) broke Search. This one-liner fixes it.
> Fix Search (broken by #188?)

- app/Http/Controllers/AlbumController.php
The "Rename All" functionality in the front end does not work with Lychee-Laravel because of an input validation issue. This one-liner fixes it.
> Support the Rename All functionality

- app/Metadata/Extractor.php
One of my cameras (Panasonic GM1) does not store lens info in `LensInfo`, but in `LensType` instead. So add `LensType` as a fallback if the other two fields we already consult yield nothing.
> Check LensType as a fallback for lens

- app/Metadata/Extractor.php
fixup invalid metadata,  which cause Laravel throw 'Malformed UTF-8 characters, possibly incorrectly encoded' error
and related album (include this jpg photo) is unable to open it.
> Extractor::extract() fixup invalid metadata,

- app/Photo.php
Smart albums are always empty for non-admin users because `Photo::OwnedBy` checks `id` rather than `owner_id`.
> Access correct id in OwnedBy

- app/Http/Middleware/UploadCheck.php
When checking upload permissions, check parent_id used with Album::add requests.
> Check parent_id when creating albums

- app/ModelFunctions/PhotoFunctions.php
If an imported photo has no EXIF, `$info['takestamp']` is actually `null`.
I'm not sure if the existing two conditions will ever trigger but since they shouldn't hurt I just added one more...
> Don't set file timestamp if takestamp is null

- app/ModelFunctions/AlbumFunctions.php
- app/ModelFunctions/PhotoFunctions.php
This will hopefully be a more portable way of detecting duplicate ids. `23505` is for PgSql, `23000` should be good for the rest.
> Use portable detection of duplicate keys

- app/ModelFunctions/PhotoFunctions.php
- app/Photo.php
Fix #223.
Don't crash if deleting a photo without a thumbnail.
Don't crash when ffmpeg is missing.
> Remaining server-side fixes for #223

- app/Http/Controllers/AlbumController.php
- app/Http/Controllers/ImportController.php
- app/Http/Controllers/PhotoController.php
- app/ModelFunctions/AlbumFunctions.php
- app/ModelFunctions/PhotoFunctions.php
- app/ModelFunctions/SessionFunctions.php
This is a first attempt to fix an issue where admin could create/move photos and albums around resulting in mixed-ownership album content, etc.
This patch ensure that all add, move, and merge operations performed by admin change the ownership of moved objects to that of the destination album, if any.
I tried to take advantage of the new session infrastructure but I wasn't always successful, e.g., in AlbumFunctions (is it possible to invoke SessionFunction from them?).
> Ensure that ownership follows parent album

- app/Http/Controllers/PhotoController.php
@ildyria, turns out that one of your changes in #236 broke the back button functionality for photos in smart albums.
This commit reverts the change and adds a comment so that we don't break it again :smiley:.
> Revert an erroneous change from #236

- resources/views/gallery.blade.php
I somehow missed this file from my user access fixes PR.
Basically, it removes the divider in the photo view between share and info buttons. In my view, that divider is unnecessary and it's unclear why it should be there (it doesn't group obviously similar operations). It is also inconsistent as there is no such divider in the album view.
> Remove a spurious divider

- app/ModelFunctions/Helpers.php
- app/Photo.php
app/Photo.php: fixup invalid shutter data "0/0 s" caused call to Helpers::gcd throws Modulo by zero exception
Helpers::gcd(): check modulo by zero error
in function `prepareData()`:
for some reason, the photo may have invalid `$photo['shutter']` data like:
`"0/0 s"`
thus, caused call to Helpers::gcd throws Modulo by zero exception
> fixup invalid shutter data "0/0 s" caused Modulo by zero exception

- app/Metadata/Extractor.php
Video preview was being displayed incorrectly because `width` and `height` were not swapped to match the video rotation tag.
> Swap width and height for rotated videos

- app/ModelFunctions/AlbumFunctions.php
- database/migrations/2019_07_13_214052_photos_wraparound.php
Trivial PR providing a configurable option to disable photo wraparound on first/last picture. It's off by default to match the current behavior.
I was actually surprised to find out that this was implemented on the server side rather than in the front end but in the end it made for an easier implementation, so no complaints. :smiley:
Note that this shouldn't go in without https://github.com/LycheeOrg/Lychee-front/pull/130 because some extra code on the front end is needed to gracefully handle missing prev/next.
> Provide option to disable first/last wraparound

- app/Http/Controllers/ImportController.php
- app/ModelFunctions/PhotoFunctions.php
- app/Photo.php
As reported by @d7415, _Import from Link_ stopped respecting the current album. Looks like I'm the one who broke it while working on _Import from Server_. Sorry!
So this trivial patch restores the previous behavior. Here's a question though: shouldn't we _always_ delete the imported file in this particular case? We are the ones who created the file by downloading the picture from the URL before importing it into Lychee. What's the point of keeping it around?
> Fix Import from Link

- app/Image/GdHandler.php
- app/Image/ImagickHandler.php
Fixes #375 
* Use the source format for small/medium with GD
* Clean up redundant/confusing calls in Imagick: `setImageFormat` had no effect; the output format is determined by the output file name extension.
> Use the source format for small/medium with GD

- app/Album.php
- app/Http/Controllers/AlbumController.php
- app/ModelFunctions/AlbumFunctions.php
- app/Photo.php
Fixes https://github.com/LycheeOrg/Lychee-front/issues/161
The issue there was the identity operator (`===`) resolving to `false` when one side was an integer and the other was a string. It could happen because we were being sloppy on the server side, especially with IDs, sometimes returning them as integers, sometimes as strings. This PR attempts to fix up all such cases that I could find, turning them into strings, which as a bonus should avoid any potential 32-bit issues as well.
> Pass numbers to the front end as strings

- app/Console/Commands/reset_admin.php
Add a `artisan lychee:reset_admin` command.
This erases the bcrypt values for `username` and `password` in the config database, allowing the re-creation of the admin logins. Pictures are not lost, it is just the authentication methods which is reset.
> Improved fix for #174

- database/migrations/2019_02_21_114356_create_pages_table.php
- database/migrations/2019_02_21_114408_create_page_contents_table.php
`pages` and `page_contents` tables migration are failed if I do `artisan migrate rollback` once.
Added conditional operator to check these tables already exists or not before do migrate these tables.
> fix: add an existing table check when migration tables

- database/migrations/2019_12_15_1000_config_check_update_every_cat_fix.php
Current configuration definition value in DB (`configs.cat`) has two values `config` and `Config`.
In 'Full Settings' appear two 'Config' sections caused by this diff.
Update `Config` to `config` for `update_check_every_days`.
Thank you.
> fix update_check_every_days value in DB from 'Config' to 'config'

- app/Configs.php
Issue #409 is caused by config parameter has_exiftool being null in the database and a later check afterwards if all config parameters are not-null. But, has_exiftool is using a 3-way logic: null = no test if exiftool available done so far; true = exiftool is available; false = not available.
Solution: Add a whitelisting feature for the check of config parameters required to be not-null.
> Fix issue 409 (has_exiftool=null in database)

- app/Assets/Helpers.php
- resources/views/frame.blade.php
- resources/views/gallery.blade.php
- resources/views/landing.blade.php
- resources/views/page.blade.php
- resources/views/view.blade.php
If `js` of `css` updated user has to clear their browser cache.
Or webserver owner has to configure their web server's cache settings just like #305 .
This PR adds UnixTimeStamp suffix to `js` and `css` just like `main.js?1576386855`
* Created `Assets\Helpers` class. And add `static function` it name is `cacheBusting`.
* This function require `filePath`.
* If file exists return `filePath` with UnixTimeStamp.
* If file does not exist return `filePath` without change.
* Wrap `js` and `css` in `*.blade.php` with `cacheBusting` function.
* Is test needed? Which directory should I add UnitTest?
JavaScript with UnixTimeStamp
CSS with UnixTimeStamp
> support cache busting feature for JavaScript and CSS

- app/Image/ImagickHandler.php
Hi :)
I'm using `Adobe Lightroom CC`. I extract JPEG from RAW and that ICC is `ProPhoto RGB`.
I notice a thumbnail color looks like dull than the original.
According to an investigation, this phenomenon occurs when ICC is not `sRGB`
Please see the following. [live data (before fix) is here](https://photo.yoshinorin.net/#15773762048402).
Imagick `stripImage` function remove all meta info.
> https://github.com/LycheeOrg/Lychee-Laravel/blob/362f85e964382616f469b96c3cdfd8c473875db1/app/Image/ImagickHandler.php#L40-L41
I found a solution from Imagick document.
> https://www.php.net/manual/en/imagick.stripimage.php
1. Extract the ICC profile
2. Strip EXIF data and image profile
3. Add the ICC profile back
I compared the thumbnail file size before and after.
* Before: 186KB
* After: 187KB
I …
> imagick: keep ICC profile when crop and scale image

- app/Configs.php
When the sanity check passes, and finds a null value, it prints nothings.
Now it should show 'NULL' instead.
> fix null print in Diagnostic

- app/Configs.php
- app/Metadata/Extractor.php
- app/ModelFunctions/PhotoFunctions.php
- database/migrations/2019_12_25_0600_config_exiftool_ternary.php
#409 has been fixed by #411 by whitelisting sanity checks for getting config values (setting still caused an error). This PR now removed again the whitelisting and introduces a proper solution changing type of has_exiftool to ternary (0,1,2).
The config variable has_exiftool was implemented as a bool and null was used in cases, test for exiftool has not yet been performed. This causes issues during sanity checks (getting config values and setting config values).
Solution: Move to ternary with the following values:
0 = Exiftool not available
1 = Exiftool is available
2 = Not yet tested
> Updated type of has_exiftool to ternary

- app/Http/Controllers/ImportController.php
Import from server is enhanced to ignore certain files
* place a file named ".lycheeignore" into the directory to be imported
* ".lycheeignore" accepts filenames, foldernames as well as * as wildcard (e.g. *.jpg)
* One line per entry
* rules are inherited to subdirectories 
* you can place ".lycheeignore" files also in subdirectories - they then only affect this subdirectory and their sub-subdirectories (but inherit additional rules from parent folders)
> Import from server: Add feature to ignore files 

- app/ModelFunctions/PhotoFunctions.php
the database field is of type `$table->string('title', 100);`
So we extend the length of possible titles to 98 characters instead of 30.
> fixes #410

- app/Photo.php
The framerate was delivered to frontend in its full beauty, potentially with a lot of decimal digits -> we truncate it at 2 decimal digits by rounding
> Format framerate to have only 2 decimal digits

- app/Configs.php
- app/Metadata/Extractor.php
- database/migrations/2020_01_04_1200_config_has_ffmpeg.php
Video upload failed in case ffmpeg was not installed.
* Added config field has_ffmpeg (0 = no ffmpeg; 1 = ffmpeg available; 2 = not tested)
* Metadata extraction first trys ffmpeg, then exiftool and uses php native tools as fallback (which only extracts mime type and filesize)
> Improve video handling in case of no ffmpeg

- app/Image/ImagickHandler.php
- app/ModelFunctions/PhotoFunctions.php
Image handling in function autorate can fail as all other functions using Imagick (e.g. width or height exceeding limits)
We should use try-catch to catch the error (issue when importing via CLI)
> Add try-catch to function autorotate for Imagick

- composer.lock
Extraction of image size failed in php-exif; Update composer.lock to use latest php-exif (see #413 )
> Fix 413 part 2

- app/Console/Commands/sync.php
- app/Http/Controllers/ImportController.php
- app/ModelFunctions/PhotoFunctions.php
This PR adds a CLI command to sync a folder (similar to Lychee-Sync)
ImportController is adjusted to be callable from CLI.
Support for some for video formats is added.
> Sync from CLI

- .travis.yml
- composer.json
- readme.md
https://www.php.net/supported-versions.php
7.2 is end of life, Security fixes only. It will be completely unsupported by 30 Nov 2020
By switching from Xenial to Bionic, I hope to get some speed on the already installed php versions.
> removing php7.2 support, moving to bionic (18.4) instead of xenial (16.4)'

- app/Configs.php
- app/Metadata/Extractor.php
- composer.lock
- database/migrations/2019_12_25_0600_config_exiftool_ternary.php
- database/migrations/2020_01_04_1200_config_has_ffmpeg.php
@SerenaButler noticed problems when `has_exiftool` is `1` and `exiftool` is installed and in the path `/usr/bin` thus findable via `which`
The problem is that `which` is not a `sh` command which may be the shell used by some php installations (not debian/ubuntu). This PR updates the composer.lock to update to the updated version of php-exif with the fix.
However this requires the user to do a `composer install`. As we may not be sure this is the case and want to fix the bug even if composer install is not done, I added a try catch. In case of exception, we read the picture again with the default php_exif library.
Nota: Did not check failure cases for the video.
Fixes #419 hopefully.
> Add try catch around the read extraction, update php-exif [composer install].

- database/migrations/2020_03_17_200000_unhide_configs.php
I'm not clear on why the SL options were hidden. If nothing else they're very useful for diagnosing issues here. I'm similarly unsure why `raw_formats` was hidden, but I feel less strongly about it being shown.
For once I have actually tested this.
> Unhide SL options and raw_formats in Diagnostics.

- app/ModelFunctions/PhotoFunctions.php
fixes #117 
fix incorrect altitude by erasing the value and notifying the user in the Logs
> fixes #117
