LycheeOrg/Lychee-Laravel

- app/Helpers.php
- app/Http/Controllers/PhotoController.php
- app/Photo.php
- database/migrations/2018_12_04_232009_create_gps_fields.php
> Extracts latitude, longitude, and altitude from EXIF data

- app/Console/Commands/exif_lens.php
- app/Console/Commands/medium.php
- app/Console/Commands/small.php
- app/Console/Commands/takedate.php
- app/Http/Controllers/ImportController.php
- app/Http/Controllers/PhotoController.php
- app/ModelFunctions/PhotoFunctions.php
- app/Providers/AppServiceProvider.php
Using Dependency Injection is better than statically calling class
methods.
> Converts the PhotoFunctions class into a service

- app/Console/Commands/exif_lens.php
- app/Console/Commands/takedate.php
- app/Metadata/Extractor.php
- app/ModelFunctions/Helpers.php
- app/ModelFunctions/PhotoFunctions.php
Also moved the GPS coordinate/altitude methods out of the Helper class
as they're not called anywhere else.
> Move metadata extraction out to its own service

- app/Image/GdHandler.php
- app/Image/ImagickHandler.php
> Replace removed accessor for compression quality

- app/Album.php
- app/Http/Controllers/AlbumController.php
Won't return albums that are hidden that do not belong to the user
requesting them.
> Checks album permissions to hide them correctly (fixes #74)

- app/Console/Commands/medium2x.php
- app/Console/Commands/small.php
- app/Console/Commands/small2x.php
Adds new `small2x` and `medium2x` commands.
Also fixes `small` and `medium`, as well as some typos in diagnostic messages.
> Implement small2x and medium2x commands

- resources/views/includes/head.blade.php
Changed viewport meta for Pinch to Zoom in and out on mobile (iPhone)
> Change viewport Meta

- app/Locale/German.php
> Small Fixes in German.php

- resources/views/landing.blade.php
- resources/views/page.blade.php
user.css working on landing page
> User css landing

- app/Album.php
- app/Configs.php
- app/Http/Controllers/AlbumController.php
- app/Http/Controllers/AlbumsController.php
- app/Http/Controllers/DiagnosticsController.php
- app/Http/Controllers/IndexController.php
- app/Http/Controllers/PageController.php
- app/Http/Controllers/SessionController.php
- app/Http/Controllers/SettingsController.php
- app/ModelFunctions/AlbumFunctions.php
- app/ModelFunctions/ConfigFunctions.php
- app/ModelFunctions/Helpers.php
- app/ModelFunctions/PhotoFunctions.php
- app/ModelFunctions/SessionFunctions.php
- app/Providers/AppServiceProvider.php
- config/defines.php
- database/migrations/2019_03_06_160454_add_website_copyrightyear.php
- database/migrations/2019_03_08_135817_private_config_fields.php
- tests/Feature/HtmlTest.php
Lots of rewriting... Started writing comments.
> Refactoring

- app/Locale/ChineseSimplified.php
- app/Locale/Dutch.php
- app/Locale/English.php
- app/Locale/French.php
- app/Locale/German.php
- app/Locale/Swedish.php
Server side of https://github.com/LycheeOrg/Lychee-front/pull/53
> New password confirmation string

- app/Http/Controllers/DiagnosticsController.php
This might help to debug furthers problems such as https://github.com/LycheeOrg/Lychee-Laravel/issues/163
> Detect 32 or 64 bits with PHP_INT_MAX

- app/Http/Controllers/ImportController.php
- database/migrations/2019_04_03_141031_php_script_limit.php
https://github.com/LycheeOrg/Lychee/issues/177
Thanks to @norey for pointing that one out.
> remove time limit for import

- app/Http/Controllers/DiagnosticsController.php
- routes/web.php
> Fix postgresql

- app/Http/Controllers/FrameController.php
- app/Http/Controllers/IndexController.php
- app/Http/Controllers/PageController.php
- app/Http/Controllers/ViewController.php
- resources/views/landing.blade.php
- resources/views/layouts/simple.blade.php
html lang attribute is now dependent of the language chosen by the user.
> add lang attribute to html

- app/Http/Controllers/PhotoController.php
- app/Metadata/GitHubFunctions.php
- public/dist/main.js
- public/dist/view.js
- routes/web.php
> Download per picture is now live

- database/migrations/2018_08_15_102039_move_albums.php
Fixes #89 
Can someone check that PR before merge ?
> Fill created_at by the takestamp of v3

- .gitignore
- app/Album.php
- app/Configs.php
- app/Http/Controllers/AlbumController.php
- app/Http/Controllers/AlbumsController.php
- app/Http/Controllers/LogController.php
- app/Logs.php
- app/ModelFunctions/PhotoFunctions.php
- app/Page.php
- app/PageContent.php
- app/Photo.php
- app/Response.php
- app/User.php
- composer.json
- composer.lock
- routes/web.php
- tests/Feature/AlbumTest.php
- tests/Feature/LangTest.php
> Add more documentation

- app/Album.php
> Fixes #192

- app/Album.php
- app/Photo.php
- app/User.php
> add cast from boolean to int

- resources/views/logs/list.blade.php
> alignment in Log

- app/Console/Commands/exif_lens.php
- app/Console/Commands/generate_thumbs.php
- app/Console/Commands/npm.php
- app/Console/Commands/takedate.php
- app/Console/Commands/video_data.php
> add progress bar, prefix all commands by 'lychee:'

- public/dist/main.js
- public/dist/view.js
> remove 404 on dist/image/placeholder.png

- app/Locale/ChineseSimplified.php
- app/Locale/Dutch.php
- app/Locale/English.php
- app/Locale/French.php
- app/Locale/German.php
- app/Locale/Swedish.php
> MoreWording: Selected instead All

- app/ModelFunctions/PhotoFunctions.php
- app/Photo.php
Fix #223 (at least a part of it).
> Gracefully handle missing FFMpeg

- app/ControllerFunctions/ReadAccessFunctions.php
- app/Http/Controllers/DiagnosticsController.php
- app/Http/Controllers/PhotoController.php
- app/Http/Controllers/SessionController.php
- app/Http/Controllers/UpdateController.php
- app/Http/Middleware/AdminCheck.php
- app/Http/Middleware/AlbumPWCheck.php
- app/Http/Middleware/LoginCheck.php
- app/Http/Middleware/UploadCheck.php
- app/ModelFunctions/AlbumFunctions.php
- app/ModelFunctions/SessionFunctions.php
- app/Photo.php
- app/Providers/AppServiceProvider.php
> Cleaning up sessions

- .travis.yml
- codecov.sh
- phpunit.xml
- readme.md
> Add coverage logging.

- database/migrations/2019_05_07_202107_fix_thumb2x_default.php
Also fix any corrupt entries in the photos table.
This is meant to be a better alternative to #238.
> Use a safe default for thumb2x

- app/Http/Controllers/ImportController.php
in normal photo upload mode,
we can upload video.
but when import from server , or  import from URL,
this code just ignored the video, 
this PR will  keep the feature consistent
> Feature: import from server or url add video support

- app/ModelFunctions/AlbumFunctions.php
> Fix top-level uploads for regular users

- app/Http/Controllers/SessionController.php
This is a prerequisite to larger changes on the front end side to prevent it from attempting to edit shared albums.
> Add username to Session::init response

- readme.md
Just slightly better looking header
> slightly better readme

- app/Album.php
- app/Http/Controllers/AlbumController.php
- app/Http/Controllers/PhotoController.php
- app/Http/Controllers/SettingsController.php
- app/ModelFunctions/PhotoFunctions.php
- database/migrations/2018_08_15_102039_move_albums.php
- database/migrations/2019_06_05_212705_fix_takestamps.php
This should correct all instances of incorrect album min/max takestamps and as a bonus be computationally much less expensive.
> Fix takestamps

- tests/Feature/PhotosTest.php
This should be fine. Just added more tests.
> more tests

- app/Exceptions/Handler.php
Server side of the fix for #100. Front end side will follow.
> Catch DecryptException and notify the front end

- app/Http/Controllers/DiagnosticsController.php
- app/Http/Controllers/FrameController.php
- app/Http/Controllers/IndexController.php
- app/Http/Controllers/LogController.php
- app/Http/Controllers/PageController.php
- app/Http/Controllers/PhotoController.php
- app/Http/Controllers/SearchController.php
- app/Http/Controllers/SettingsController.php
- app/Http/Controllers/SharingController.php
- app/Http/Controllers/UserController.php
- app/Http/Controllers/ViewController.php
- app/Http/Middleware/RedirectIfAuthenticated.php
- app/Http/Middleware/VerifyCsrfToken.php
- app/Metadata/Extractor.php
- app/ModelFunctions/AlbumFunctions.php
- app/ModelFunctions/PhotoFunctions.php
> fixes lack of documentation

- app/Http/Controllers/SessionController.php
- database/migrations/2019_06_17_123718_hide_version_number.php
- public/dist/main.js
fixes https://github.com/LycheeOrg/Lychee-Laravel/issues/282
> Hide version

- app/Http/Controllers/PhotoController.php
- app/Photo.php
- tests/Feature/PhotosTest.php
I never use tags but while testing something I noticed that the attempt to remove the last tag of an image results in a server error.
> Fix tags delete

- app/Http/Controllers/SearchController.php
Just like title says:
fixes #301
> fixes #301

- app/Http/Controllers/AlbumController.php
- app/Http/Controllers/FrameController.php
- app/Http/Controllers/PhotoController.php
- app/Metadata/Extractor.php
- app/ModelFunctions/PhotoFunctions.php
- app/ModelFunctions/SymLinkFunctions.php
- app/Photo.php
- app/SymLink.php
- database/migrations/2019_09_14_205647_config_raw_files.php
- public/.gitignore
- public/dist/main.js
- public/dist/view.js
fixes #284 
We add a new config field: `raw_formats` it takes as input a string containing the extensions wanted. eg: `.tex|.cr2|.cr3`
**We do not do anything on raw files.** We just upload them to the new `uploads/raw` folder.
In order to avoid broken image logo we use `img/placeholder.png` instead of the the file.
The content of the file, e.g. for a `.tex` file is still visible via direct link.
Symlinking, Album Download, Photo Download should also work.
> add basic raw support.

- app/Http/Controllers/PhotoController.php
- app/Metadata/Extractor.php
- app/ModelFunctions/PhotoFunctions.php
- app/Photo.php
- database/migrations/2019_09_20_110936_add_img_direction.php
The Exif data also stores the direction of the image.
For simplification, the commit ignores the difference between true and magnetic north.
> Extract image direction data from Exif

- app/Metadata/DiskUsage.php
Remove some of the hard coding of the paths (`/` / `C:`), no need for differentiation with the `base_path()` function provided by Laravel.
Added some FIXME for later work...
> Fixes #351

- app/Http/Controllers/FrameController.php
- app/Http/Controllers/PhotoController.php
- database/migrations/2019_10_03_214750_frame_refresh_in_sec.php
- public/dist/main.js
- public/dist/view.js
- tests/Feature/FrameTest.php
* Change Mod_Frame_refresh unit to seconds
* Add optional albumID argument to Photo::duplicate
> Various fixes

- app/ModelFunctions/Helpers.php
- database/migrations/2019_10_06_152017_add_force_32bit_ids.php
As discussed... Resolves weird issues with 64-bit IDs on some hosts.
> Add an option to force 32-bit IDs

- app/Http/Controllers/ImportController.php
- app/ModelFunctions/PhotoFunctions.php
> Skip duplicate albums with skip_duplicates

- app/Http/Controllers/PhotoController.php
> Don't sort as this prevents randomization

- composer.json
- composer.lock
The Laravel 6.x requires PHP `7.2.0`.
> [Server Requirements](https://laravel.com/docs/6.x/installation#server-requirements)
IMHO should update the PHP version of the composer to `7.2.0`
Thanks :)
> update php version of composer

- app/Metadata/Extractor.php
- composer.lock
> Fix issue 413

- app/Http/Middleware/VerifyCsrfToken.php
> Fixes #417

- app/Photo.php
fixes https://github.com/LycheeOrg/Lychee-Laravel/issues/444
I'm not a PHP developer, If you wish to add unit test for this, you can edit this PR.
> Fix photo isDuplicate detection

- app/Http/Controllers/ImportController.php
https://github.com/LycheeOrg/Lychee-Laravel/blob/4f422b7a2fd61edf0d47bdf11dffe6f943710e2d/app/Http/Controllers/ImportController.php#L230-L242
> You only need ob_flush() if an output buffer is active (for example by ob_start(), or by configuration settings). If you haven't, just remove the ob_flush(). Or you can make it conditional:
https://stackoverflow.com/a/9182133
```
"Status: \/var\/www\/html\/Lychee-Laravel\/public\/uploads\/import\/: 0\n{
"message": "ob_flush(): failed to flush buffer. No buffer to flush",
"exception": "ErrorException",
"file": "/var/www/html/Lychee-Laravel/app/Http/Controllers/ImportController.php",
"line": 237,
"trace": [
{
"function": "handleError",
"class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
"type": "->"
},
{
"file": …
```
> Fixes ob_flush() error from 'import from Server'

- makefile
- routes/web.php
> small fix redirect on /gallery instead of sql error
